/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidptrace_PtraceLib */

#ifndef _Included_com_example_androidptrace_PtraceLib
#define _Included_com_example_androidptrace_PtraceLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidptrace_PtraceLib
 * Method:    syscall_trace
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidptrace_PtraceLib_syscall_1trace
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
